name: Docker Image CI

on:
  [workflow_dispatch]


jobs:

  publish_image:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cbarnthouse/ha-custom:latest

    - name: Publish
      run: |
        docker login -u cbarnthouse -p ${{ secrets.docker_hub_token }}
        docker push cbarnthouse/ha-custom:latest
